export interface EnemyTemplate {
  id: string;
  name: string;
  hp: number;
  minDamage: number;
  maxDamage: number;
  defense: number;
  speed: number;
  dodge: number;
  accuracy: number;
  critChance: number;
  critDamage: number;
}

export const ENEMIES: Record<string, EnemyTemplate> = {
  wild_shrew: {
    id: 'wild_shrew',
    name: 'Дикая землеройка',
    hp: 32,
    minDamage: 4,
    maxDamage: 7,
    defense: 0,
    speed: 8,
    dodge: 5,
    accuracy: 90,
    critChance: 3,
    critDamage: 150,
  },
  stone_scavenger: {
    id: 'stone_scavenger',
    name: 'Каменный падальщик',
    hp: 44,
    minDamage: 5,
    maxDamage: 8,
    defense: 1,
    speed: 7,
    dodge: 4,
    accuracy: 88,
    critChance: 4,
    critDamage: 150,
  },
  mine_crawler: {
    id: 'mine_crawler',
    name: 'Шахтный ползун',
    hp: 55,
    minDamage: 4,
    maxDamage: 7,
    defense: 2,
    speed: 6,
    dodge: 2,
    accuracy: 88,
    critChance: 4,
    critDamage: 150,
  },
  soot_mite: {
    id: 'soot_mite',
    name: 'Сажевый клещ',
    hp: 28,
    minDamage: 3,
    maxDamage: 5,
    defense: 0,
    speed: 12,
    dodge: 8,
    accuracy: 85,
    critChance: 4,
    critDamage: 140,
  },
  moss_boar: {
    id: 'moss_boar',
    name: 'Моховой хряк',
    hp: 48,
    minDamage: 5,
    maxDamage: 8,
    defense: 1,
    speed: 7,
    dodge: 3,
    accuracy: 88,
    critChance: 4,
    critDamage: 150,
  },
  needle_runner: {
    id: 'needle_runner',
    name: 'Хвоебег',
    hp: 36,
    minDamage: 4,
    maxDamage: 7,
    defense: 0,
    speed: 14,
    dodge: 10,
    accuracy: 90,
    critChance: 6,
    critDamage: 150,
  },
  pitch_mite: {
    id: 'pitch_mite',
    name: 'Смоляной клещ',
    hp: 52,
    minDamage: 5,
    maxDamage: 8,
    defense: 2,
    speed: 9,
    dodge: 5,
    accuracy: 88,
    critChance: 5,
    critDamage: 150,
  },
  resin_brute: {
    id: 'resin_brute',
    name: 'Смоляной громила',
    hp: 78,
    minDamage: 7,
    maxDamage: 11,
    defense: 3,
    speed: 5,
    dodge: 2,
    accuracy: 86,
    critChance: 4,
    critDamage: 160,
  },
  stumpfang: {
    id: 'stumpfang',
    name: 'Пнеклык',
    hp: 110,
    minDamage: 8,
    maxDamage: 12,
    defense: 3,
    speed: 4,
    dodge: 2,
    accuracy: 90,
    critChance: 5,
    critDamage: 160,
  },
  yara_trace: {
    id: 'yara_trace',
    name: 'След Яры',
    hp: 70,
    minDamage: 6,
    maxDamage: 9,
    defense: 2,
    speed: 9,
    dodge: 6,
    accuracy: 90,
    critChance: 6,
    critDamage: 150,
  },
  wedge_scout: {
    id: 'wedge_scout',
    name: 'Разведчик клина',
    hp: 62,
    minDamage: 5,
    maxDamage: 8,
    defense: 1,
    speed: 11,
    dodge: 8,
    accuracy: 88,
    critChance: 5,
    critDamage: 150,
  },
  foreign_post: {
    id: 'foreign_post',
    name: 'Чужой заступ',
    hp: 80,
    minDamage: 6,
    maxDamage: 10,
    defense: 3,
    speed: 7,
    dodge: 4,
    accuracy: 90,
    critChance: 4,
    critDamage: 150,
  },
  wenzel_warden: {
    id: 'wenzel_warden',
    name: 'Вензель',
    hp: 140,
    minDamage: 8,
    maxDamage: 13,
    defense: 4,
    speed: 5,
    dodge: 3,
    accuracy: 90,
    critChance: 6,
    critDamage: 170,
  },
};

export const UNKNOWN_NODE7_CREATURE = {
  id: 'unknown_node7_creature',
  name: '???',
} as const;

export function getEnemy(id: string): EnemyTemplate | undefined {
  return ENEMIES[id];
}
