export const STORY_FLAGS = [
  'found_rusty_token',
  'activated_node7_token',
  'met_rem',
  'node7_gate_closed',
  'fed_stone_scavenger',
  'stone_scavenger_affinity',
  'showed_token_to_rem',
  'hid_token_from_rem',
  'opened_start_crate',
  'temporary_shelter_level',
  'heard_mine_crawler',
  'unknown_blue_mineral',
  'day_1_complete',
  'visited_forest_clearing',
  'visited_rem_camp',
  'visited_stone_scree',
  'visited_old_adit',
  'visited_node_7',
  'visited_secret_chamber',
  'defeated_wild_shrew',
  'defeated_mine_crawler',
  'defeated_stone_scavenger',
  'night_eavesdropped',
  'night_pretended_sleep',
  'slept_at_rem',
  'slept_at_shelter',
  'scavenger_extra_stone',
  'found_broken_lantern',
  'found_blue_light',
  'iron_ready',
  'player_camp_founded',
  'camp_on_shelter',
  'camp_table_placed',
  'camp_chest_built',
  'camp_fire_built',
  'found_coal',
  'camp_lit',
  'seen_soot_fissure',
  'scavenger_day2_visit',
  'scavenger_cache',
  'pressed_rem_about_night',
  'seen_ridge_tracks',
  'day_2_complete',
] as const;

export type StoryFlag = (typeof STORY_FLAGS)[number];
