import type { EquipmentSlot, Rarity } from '@kubolesie/shared';

export interface ItemTemplate {
  id: string;
  name: string;
  description: string;
  rarity: Rarity;
  slot?: EquipmentSlot;
  questItem?: boolean;
  consumable?: boolean;
  energyRestore?: number;
  attackBonus?: number;
  defenseBonus?: number;
  dodgeBonus?: number;
  maxEnergyBonus?: number;
  woodYieldBonus?: number;
  stoneYieldBonus?: number;
  oreYieldBonus?: number;
  minDamage?: number;
  maxDamage?: number;
}

export const ITEM_TEMPLATES: Record<string, ItemTemplate> = {
  stone_knife: {
    id: 'stone_knife',
    name: 'Каменный нож',
    description: 'На рукояти выцарабан тот же знак, что на ржавом жетоне.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 3,
    minDamage: 3,
    maxDamage: 5,
  },
  crafting_table: {
    id: 'crafting_table',
    name: 'Верстак',
    description: 'Грубый кубический стол. Без него кирку не сколотить.',
    rarity: 'COMMON',
  },
  wooden_axe: {
    id: 'wooden_axe',
    name: 'Деревянный топор',
    description: 'Лучше рубит брёвна, чем голые руки.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 2,
    minDamage: 2,
    maxDamage: 3,
    woodYieldBonus: 0.25,
  },
  wooden_pickaxe: {
    id: 'wooden_pickaxe',
    name: 'Деревянная кирка',
    description: 'Берёт булыжник. Железо ей не по зубам.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 2,
    minDamage: 2,
    maxDamage: 3,
    stoneYieldBonus: 0.15,
  },
  stone_axe: {
    id: 'stone_axe',
    name: 'Каменный топор',
    description: 'Топор из булыжника. Лучше рубит дерево.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 2,
    minDamage: 2,
    maxDamage: 4,
    woodYieldBonus: 0.25,
  },
  stone_pickaxe: {
    id: 'stone_pickaxe',
    name: 'Каменная кирка',
    description: 'Для булыжника и железной жилы.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 2,
    minDamage: 2,
    maxDamage: 3,
    stoneYieldBonus: 0.3,
    oreYieldBonus: 0.3,
  },
  worn_gloves: {
    id: 'worn_gloves',
    name: 'Потёртые перчатки',
    description: 'Едва держатся на руках.',
    rarity: 'COMMON',
    slot: 'HANDS',
    defenseBonus: 2,
  },
  miner_belt: {
    id: 'miner_belt',
    name: 'Шахтёрский пояс',
    description: 'Карманы для руды и клиньев.',
    rarity: 'UNCOMMON',
    slot: 'CHEST',
    defenseBonus: 3,
    maxEnergyBonus: 2,
  },
  rusty_token: {
    id: 'rusty_token',
    name: 'Ржавый жетон',
    description: 'Жетон с выбитой семёркой. Квестовый предмет.',
    rarity: 'UNCOMMON',
    questItem: true,
  },
  dry_rusk: {
    id: 'dry_rusk',
    name: 'Сухой сухарь',
    description: 'Жёсткий, но восстанавливает силы.',
    rarity: 'COMMON',
    consumable: true,
    energyRestore: 5,
  },
  broken_lantern: {
    id: 'broken_lantern',
    name: 'Сломанный фонарь',
    description: 'Стекло выбито. Ещё пригодится.',
    rarity: 'COMMON',
    questItem: true,
  },
  torch: {
    id: 'torch',
    name: 'Факел',
    description: 'Уголь и палка. Свет без печи.',
    rarity: 'COMMON',
  },
  chest: {
    id: 'chest',
    name: 'Сундук',
    description: 'Восемь досок. Пока просто стоит на стане.',
    rarity: 'COMMON',
  },
  campfire: {
    id: 'campfire',
    name: 'Костёр',
    description: 'Брёвна, палки, уголь. Ночь становится короче.',
    rarity: 'COMMON',
  },
  wooden_sword: {
    id: 'wooden_sword',
    name: 'Деревянный меч',
    description: 'Две доски и палка. Слабее камня, лучше кирки в бою.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 3,
    minDamage: 3,
    maxDamage: 4,
  },
  stone_sword: {
    id: 'stone_sword',
    name: 'Каменный меч',
    description: 'Рвёт смолу. Заметно лучше ножа.',
    rarity: 'COMMON',
    slot: 'WEAPON',
    attackBonus: 4,
    minDamage: 4,
    maxDamage: 6,
  },
  hide_tunic: {
    id: 'hide_tunic',
    name: 'Туника из шкуры',
    description: 'Восемь шкур. Держит клыки хряка.',
    rarity: 'COMMON',
    slot: 'CHEST',
    defenseBonus: 4,
  },
  stumpfang_tooth: {
    id: 'stumpfang_tooth',
    name: 'Клык Пнеклыка',
    description: 'Трофей мини-босса. Вел его оценит. Рем — нет.',
    rarity: 'UNCOMMON',
    questItem: true,
  },
  wedge_map_fragment: {
    id: 'wedge_map_fragment',
    name: 'Фрагмент карты',
    description: 'Семёрка и ещё одна метка в стороне.',
    rarity: 'UNCOMMON',
    questItem: true,
  },
  furnace: {
    id: 'furnace',
    name: 'Печь',
    description: 'Восемь булыжников. Руда течёт. Синее — нет.',
    rarity: 'COMMON',
  },
  iron_pickaxe: {
    id: 'iron_pickaxe',
    name: 'Железная кирка',
    description: 'Копает жилу глубже каменной.',
    rarity: 'UNCOMMON',
    slot: 'WEAPON',
    attackBonus: 4,
    minDamage: 3,
    maxDamage: 5,
    stoneYieldBonus: 0.4,
    oreYieldBonus: 0.5,
  },
  iron_axe: {
    id: 'iron_axe',
    name: 'Железный топор',
    description: 'Брёвна и баррикады. Ломает деревянную ногу.',
    rarity: 'UNCOMMON',
    slot: 'WEAPON',
    attackBonus: 4,
    minDamage: 4,
    maxDamage: 6,
    woodYieldBonus: 0.4,
  },
  iron_sword: {
    id: 'iron_sword',
    name: 'Железный меч',
    description: 'Лучший DPS недели до босса.',
    rarity: 'UNCOMMON',
    slot: 'WEAPON',
    attackBonus: 6,
    minDamage: 6,
    maxDamage: 9,
  },
  glass_pane: {
    id: 'glass_pane',
    name: 'Стекло',
    description: 'Вел носит стёкла. Оправа для фонаря.',
    rarity: 'UNCOMMON',
  },
  lit_lantern: {
    id: 'lit_lantern',
    name: 'Зажжённый фонарь',
    description: 'Шарниры видны. Темнота — нет.',
    rarity: 'UNCOMMON',
    questItem: true,
  },
  resin_mail: {
    id: 'resin_mail',
    name: 'Смоляная кольчуга',
    description: 'Редкая. Тяжёлая. Смола гасит удар.',
    rarity: 'RARE',
    slot: 'CHEST',
    defenseBonus: 6,
  },
  wedge_charm: {
    id: 'wedge_charm',
    name: 'Чар клина',
    description: 'Редкий. Уклон в смоле.',
    rarity: 'RARE',
    slot: 'AMULET',
    dodgeBonus: 8,
  },
  pvp_token: {
    id: 'pvp_token',
    name: 'Жетон спора',
    description: 'Мало стоит. Не лучший фарм монет.',
    rarity: 'COMMON',
  },
  wenzel_plate: {
    id: 'wenzel_plate',
    name: 'Пластина Вензеля',
    description: 'Уникальный материал внешнего стража.',
    rarity: 'RARE',
    questItem: true,
  },
  hinge_charm: {
    id: 'hinge_charm',
    name: 'Шарнирный оберег',
    description: 'Def и капля энергии. С петлей затвора.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 2,
    maxEnergyBonus: 2,
  },
  seal_shard_7: {
    id: 'seal_shard_7',
    name: 'Осколок печати',
    description: 'Сюжетный ключ. Один из семи. Не объясняет остальные.',
    rarity: 'EPIC',
    questItem: true,
  },
  stone_hoe: {
    id: 'stone_hoe',
    name: 'Каменная мотыга',
    description: 'Два булыжника, две палки. Пашет клетку у стана.',
    rarity: 'COMMON',
  },
  iron_hoe: {
    id: 'iron_hoe',
    name: 'Железная мотыга',
    description: 'Грядка слушается быстрее каменной.',
    rarity: 'UNCOMMON',
  },
  bow: {
    id: 'bow',
    name: 'Лук',
    description: 'Три палки, три нити. Первый удар до схватки.',
    rarity: 'UNCOMMON',
    slot: 'WEAPON',
    attackBonus: 5,
    minDamage: 5,
    maxDamage: 8,
  },
  shield: {
    id: 'shield',
    name: 'Щит',
    description: 'Шесть досок и слиток. Держит тяжёлый удар.',
    rarity: 'UNCOMMON',
    defenseBonus: 4,
  },
  bucket: {
    id: 'bucket',
    name: 'Ведро',
    description: 'Три слитка. Воду убрать, набрать, полить. Не океан.',
    rarity: 'UNCOMMON',
  },
  bread: {
    id: 'bread',
    name: 'Хлеб',
    description: 'Три пшеницы. Сытнее сухаря.',
    rarity: 'COMMON',
    consumable: true,
    energyRestore: 8,
  },
  mist_charm: {
    id: 'mist_charm',
    name: 'Туманный оберег',
    description: 'Уникальный. Не делает бессмертным. Низина чуть реже кусает.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 1,
    dodgeBonus: 5,
  },
  seal_shard_6: {
    id: 'seal_shard_6',
    name: 'Осколок второй печати',
    description: 'Сюжетный ключ. Второй из семи.',
    rarity: 'EPIC',
    questItem: true,
  },
  drowned_pearl: {
    id: 'drowned_pearl',
    name: 'Топяная жемчужина',
    description: 'Редкая. С короткого затопленного пути.',
    rarity: 'RARE',
    slot: 'RING',
    dodgeBonus: 3,
  },
  root_rope: {
    id: 'root_rope',
    name: 'Корневая верёвка',
    description: 'Живое волокно. Короткий путь через завал. Не инструмент нового яруса.',
    rarity: 'UNCOMMON',
  },
  root_brace: {
    id: 'root_brace',
    name: 'Укреплённый настил',
    description: 'Брёвна, камень, слиток. Держит удар Корнеплёта и Вязеня.',
    rarity: 'UNCOMMON',
    defenseBonus: 2,
  },
  root_charm: {
    id: 'root_charm',
    name: 'Корневой оберег',
    description: 'Уникальный. Чаща чуть реже хватает за щиколотку.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 2,
    dodgeBonus: 4,
  },
  seal_shard_5: {
    id: 'seal_shard_5',
    name: 'Осколок третьей печати',
    description: 'Сюжетный ключ. Третий из семи.',
    rarity: 'EPIC',
    questItem: true,
  },
  rot_binding: {
    id: 'rot_binding',
    name: 'Гнилая связка',
    description: 'Смола, волокно и палка. Короткий угол против Чернокорня. Не новый ярус инструмента.',
    rarity: 'UNCOMMON',
  },
  path_marker: {
    id: 'path_marker',
    name: 'Метка пути',
    description: 'Доски, уголь и гнилая смола. Кладётся у ядра. Не ломает сеть — читает правку.',
    rarity: 'UNCOMMON',
  },
  path_charm: {
    id: 'path_charm',
    name: 'Оберег тропы',
    description: 'Уникальный. Тропа чуть реже врёт под ногой.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 1,
    dodgeBonus: 5,
  },
  seal_shard_4: {
    id: 'seal_shard_4',
    name: 'Осколок четвёртой печати',
    description: 'Сюжетный ключ. Четвёртый из семи.',
    rarity: 'EPIC',
    questItem: true,
  },
  reed_rope: {
    id: 'reed_rope',
    name: 'Камышовая связка',
    description: 'Чёрный камыш, волокно и палка. Короткий угол против Топежора. Не новый ярус инструмента.',
    rarity: 'UNCOMMON',
  },
  marsh_platform: {
    id: 'marsh_platform',
    name: 'Топяной настил',
    description: 'Доски, камыш и слиток. Держит ногу над чёрной водой. Не ломает сеть.',
    rarity: 'UNCOMMON',
  },
  mire_charm: {
    id: 'mire_charm',
    name: 'Оберег топи',
    description: 'Уникальный. Топь чуть реже хватает за щиколотку.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 1,
    dodgeBonus: 5,
  },
  seal_shard_3: {
    id: 'seal_shard_3',
    name: 'Осколок пятой печати',
    description: 'Сюжетный ключ. Пятый найденный. Identifier = 3.',
    rarity: 'EPIC',
    questItem: true,
  },
  haul_line: {
    id: 'haul_line',
    name: 'Тяговый канат',
    description: 'Волокно, палка и механический лом. Короткий угол против Скрежетника. Не новый ярус инструмента.',
    rarity: 'UNCOMMON',
  },
  mechanical_brace: {
    id: 'mechanical_brace',
    name: 'Механическая распорка',
    description: 'Доски, лом и слиток. Держит площадку над затвором. Не ломает сеть.',
    rarity: 'UNCOMMON',
  },
  lock_charm: {
    id: 'lock_charm',
    name: 'Оберег затвора',
    description: 'Уникальный. Старые крепления чуть реже срываются.',
    rarity: 'RARE',
    slot: 'AMULET',
    defenseBonus: 1,
    dodgeBonus: 5,
  },
  seal_shard_2: {
    id: 'seal_shard_2',
    name: 'Осколок шестой печати',
    description: 'Сюжетный ключ. Шестой найденный. Identifier = 2.',
    rarity: 'EPIC',
    questItem: true,
  },
};

export const STONE_SALVAGE_TOOLS = ['stone_pickaxe', 'stone_axe', 'stone_sword'] as const;

export function getItemTemplate(id: string): ItemTemplate | undefined {
  return ITEM_TEMPLATES[id];
}
